name: Build and Push Image
on:
  push:
    paths:
      - images/**
env:
  IMAGE_VERSION: 0.7-ppc64le
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v2
      with:
        username: ahendre3
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: quay.io
    - uses: docker/build-push-action@v3
      with:
        file: images/docker-in-docker/Dockerfile
        tags: quay.io/ahendre3/docker-ce-build:latest
        platforms: linux/ppc64le
        push: true      
